stages:
- build
- test

build-all:
  image: microsoft/dotnet:2.1-sdk-alpine
  stage: build
  script:
  - dotnet publish -c release src/cli/ -o dist/
  - dotnet publish -c release tools/data-gen/ -o dist/
  artifacts:
    paths:
    - src/cli/dist
    - tools/data-gen/dist
  tags:
  - docker

build-docs:
  image: dbogatov/docker-images:doxygen-latest
  stage: build
  script:
  - rm -rf documentation
	- mkdir -p documentation
	- doxygen Doxyfile
  artifacts:
    paths:
    - documentation
  tags:
  - docker

unit-tests:
  image: microsoft/dotnet:2.1-sdk-alpine
  stage: test
  script:
  - apk add --update bash
  - ./test/test.sh
  tags:
  - docker

integration-tests:
  image: microsoft/dotnet:2.1-runtime-alpine
  stage: test
  script:
  - apk add --update bash
  - ./tools/data-gen/generate.sh -d 100 -q 20 -s 1305 -n
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/exact-queries.txt -v
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/range-0.5-queries.txt --queries-type range -v
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/range-1-queries.txt --queries-type range -v
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/range-2-queries.txt --queries-type range -v
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/range-3-queries.txt --queries-type range -v
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/update-queries.txt --queries-type update -v
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/delete-queries.txt --queries-type delete -v
  tags:
  - docker
