stages:
- build
- test


build-all:
  image: microsoft/dotnet:2.1-sdk-alpine
  stage: build
  script:
  - dotnet publish -c release src/cli/ -o dist/
  artifacts:
    paths:
    - src/cli/dist
  tags:
  - docker

unit-tests:
  image: microsoft/dotnet:2.1-sdk
  stage: test
  script:
  - apk add --update bash
  - dotnet restore -v diag test/
  - ./test/test.sh
  tags:
  - docker

integration-tests:
  image: microsoft/dotnet:2.1-runtime-alpine
  stage: test
  script:
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/exact-queries.txt
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/range-queries.txt --queries-type range
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/update-queries.txt --queries-type update
  - dotnet src/cli/dist/cli.dll --dataset data/dataset.txt --queries data/delete-queries.txt --queries-type delete
  tags:
  - docker
